PreCommit:
  ALL:
    quiet: true
  # Defaults enabled: AuthorEmail, AuthorName,
  # BrokenSymlinks, CaseConflicts, MergeConflicts
  FixMe: { enabled: true }
  ForbiddenBranches: { enabled: true }
  GoLint: { enabled: true }
  JsonSyntax: { enabled: true }
  LicenseFinder: { enabled: true }
  LineEndings: { enabled: true }
  ShellCheck: { enabled: true }
  TrailingWhitespace: { enabled: true }
  YamlLint: { enabled: true }
  YamlSyntax: { enabled: true }

CommitMsg:
  ALL:
    quiet: true
  # Defaults enabled: CapitalizedSubject, EmptyMessage,
  # SingleLineSubject, TextWidth, TrailingPeriod

PostCommit: # Defaults enabled: none
PostRewrite: # Defaults enabled: none
PostCheckout: # Defaults enabled: none
PostMerge: # Defaults enabled: none
PreRebase: # Defaults enabled: none
PrePush: # Defaults enabled: none
