title: actions
email: mark@philoserf.com
description: AKA a collections of docker images
baseurl: "/actions"
url: "https://philoserf.github.io"
twitter_username: philoserf
github_username: philoserf

# Build settings
markdown: kramdown
theme: minima
destination: ./build
plugins:
  - jekyll-asciidoc
exclude:
  - README.adoc
  - LICENSE
  - Makefile
  - Gemfile.lock
  - CODE_OF_CONDUCT.adoc
  - CONTRIBUTING.adoc
  - markdownlint/
  - pandoc/
  - build/
  - Gemfile
  - base/

asciidoc: {}
asciidoctor:
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
