version: "3"

tasks:
  default:
    cmd:
      - task: lint

  lint:
    desc: all lint tasks
    cmd:
      - task: markdownlint
      - task: yamllint
      - task: hadolint

  markdownlint:
    desc: markdown lint tasks
    cmd:
      - markdownlint --fix .github/**/*.md **/*.md

  yamllint:
    desc: yaml lint tasks
    cmd:
      - yamllint .*.yaml .yamllint

  hadolint:
    desc: dockerfile lint tasks
    cmd:
      - hadolint **/Dockerfile
