version: "3"

tasks:
  default:
    cmds:
      - task: lint

  lint:
    desc: all lint tasks
    cmds:
      - task: markdownlint
      - task: yamllint
      - task: hadolint

  markdownlint:
    desc: markdown lint tasks
    cmds:
      - markdownlint .

  yamllint:
    desc: yaml lint tasks
    cmds:
      - yamllint --strict .

  hadolint:
    desc: container definition lint tasks
    cmds:
      - hadolint **/Dockerfile
