FROM alpine:3

LABEL "maintainer"="Mark Ayers <mark@philoserf.com>"
LABEL "repository"="https://github.com/philoserf/actions"
LABEL "homepage"="https://philoserf.github.io/actions"

LABEL "com.github.actions.name"="base"
LABEL "com.github.actions.description"="a base for all other actions"
LABEL "com.github.actions.color"="white"
LABEL "com.github.actions.icon"="check"

RUN adduser -D -u 1000 -h /home/runner -s /bin/sh runner
WORKDIR /home/runner
USER runner
ENTRYPOINT ["/bin/sh"]
